name: CI/CD for VS Code Extension

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # 3. 安装 xvfb
      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      # 4. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 5. 构建扩展
      - name: Build
        run: npm run compile

      # 6. 执行代码检查（可选择使用 ESLint 或其他工具）
      - name: Lint Code with ESLint
        run: npm run lint

      # 7. 执行测试
      - name: Run Tests with xvfb
        run: xvfb-run --auto-servernum npm test

      # 8. 构建扩展
      - name: Package Extension
        run: npm run package

  # 可选：自动发布到 Visual Studio Marketplace
  # 需要在 GitHub Secrets 中配置 `VSCE_TOKEN`
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        run: npm run package

      - name: Publish to Visual Studio Marketplace
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm install -g @vscode/vsce
          vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
